steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'docker'
  args: ['build',
          '--tag=europe-west1-docker.pkg.dev/$PROJECT_ID/snowplow/collector-pubsub:$BUILD_ID',
          '.']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'europe-west1-docker.pkg.dev/$PROJECT_ID/snowplow/collector-pubsub:$BUILD_ID']

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: gcloud
  args: [
    'run', 'deploy',
    'snowplow-collector', '--image', 'europe-west1-docker.pkg.dev/$PROJECT_ID/snowplow/collector-pubsub:$BUILD_ID',
    '--region', 'europe-west1',
    '--platform', 'managed',
    '--allow-unauthenticated',
    ]